require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Assemblerd to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AssemblersController do
  render_views

  describe "access control" do
    it "should deny access to 'create'" do
      post :create
      response.should redirect_to(signin_path)
    end
    
    it "should deny access to 'destroy'" do
      delete :destroy, :id => 1
      response.should redirect_to(signin_path)
    end
  end
  
  describe "POST 'create'" do
    
    before(:each) do
      @user = test_sign_in(Factory(:user))
@user.should_not ==  nil
    end

    describe "failure" do

      before(:each) do
        @attr = { :chapter => "" }
      end

      it "should not create a assembler" do
        lambda do
          post :create, :assembler => @attr
        end.should_not change(Assembler, :count)
      end
      
      it "should re-render the home page" do
        post :create, :assembler => @attr
        response.should render_template('assemblers/new')
      end
    end

    describe "success" do
      
      before(:each) do
        @attr = { :chapter => "Lorem ipsum dolor sit amet" }
      end
      
      it "should create a assembler" do
        lambda do
          post :create, :assembler => @attr
        end.should change(Assembler, :count).by(1)
      end
      
      it "should redirect to the root path" do
        post :create, :assembler => @attr
        response.should redirect_to assemblers_path
                                    #(:user_id => @user))
      end

      it "should have a flash success message" do
        post :create, :assembler => @attr
        flash[:success].should =~ /assembler created/i
      end
    end
  end

  describe "DELETE 'destroy'" do

    describe "for an unauthorized user" do
      
      before(:each) do
        @user = Factory(:user)
        wrong_user = Factory(:user, :email => Factory.next(:email))
        @assembler = Factory(:assembler, :user => @user)
        test_sign_in(wrong_user)
      end

      it "should deny access" do
        delete :destroy, :id => @assembler
        response.should redirect_to(root_path)
      end
    end
    
    describe "for an authorized user" do
      
      before(:each) do
        @user = test_sign_in(Factory(:user))
        
        @user.should_not == nil
        @assembler = Factory(:assembler, :user_id => @user)
        #@assembler.should == nil
      end
      
      it "should destroy the assembler" do
        lambda do
          delete :destroy, :id => @assembler
          flash[:success].should =~ /deleted/i
          response.should redirect_to(assemblers_path)
        end.should change(Assembler, :count).by(-1)
      end
    end
  end

end
