require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BravesController do

  # This should return the minimal set of attributes required to create a valid
  # Brave. As you add validations to Brave, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all braves as @braves" do
      brave = Brave.create! valid_attributes
      get :index
      assigns(:braves).should eq([brave])
    end
  end

  describe "GET show" do
    it "assigns the requested brave as @brave" do
      brave = Brave.create! valid_attributes
      get :show, :id => brave.id.to_s
      assigns(:brave).should eq(brave)
    end
  end

  describe "GET new" do
    it "assigns a new brave as @brave" do
      get :new
      assigns(:brave).should be_a_new(Brave)
    end
  end

  describe "GET edit" do
    it "assigns the requested brave as @brave" do
      brave = Brave.create! valid_attributes
      get :edit, :id => brave.id.to_s
      assigns(:brave).should eq(brave)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Brave" do
        expect {
          post :create, :brave => valid_attributes
        }.to change(Brave, :count).by(1)
      end

      it "assigns a newly created brave as @brave" do
        post :create, :brave => valid_attributes
        assigns(:brave).should be_a(Brave)
        assigns(:brave).should be_persisted
      end

      it "redirects to the created brave" do
        post :create, :brave => valid_attributes
        response.should redirect_to(Brave.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved brave as @brave" do
        # Trigger the behavior that occurs when invalid params are submitted
        Brave.any_instance.stub(:save).and_return(false)
        post :create, :brave => {}
        assigns(:brave).should be_a_new(Brave)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Brave.any_instance.stub(:save).and_return(false)
        post :create, :brave => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested brave" do
        brave = Brave.create! valid_attributes
        # Assuming there are no other braves in the database, this
        # specifies that the Brave created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Brave.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => brave.id, :brave => {'these' => 'params'}
      end

      it "assigns the requested brave as @brave" do
        brave = Brave.create! valid_attributes
        put :update, :id => brave.id, :brave => valid_attributes
        assigns(:brave).should eq(brave)
      end

      it "redirects to the brave" do
        brave = Brave.create! valid_attributes
        put :update, :id => brave.id, :brave => valid_attributes
        response.should redirect_to(brave)
      end
    end

    describe "with invalid params" do
      it "assigns the brave as @brave" do
        brave = Brave.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Brave.any_instance.stub(:save).and_return(false)
        put :update, :id => brave.id.to_s, :brave => {}
        assigns(:brave).should eq(brave)
      end

      it "re-renders the 'edit' template" do
        brave = Brave.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Brave.any_instance.stub(:save).and_return(false)
        put :update, :id => brave.id.to_s, :brave => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested brave" do
      brave = Brave.create! valid_attributes
      expect {
        delete :destroy, :id => brave.id.to_s
      }.to change(Brave, :count).by(-1)
    end

    it "redirects to the braves list" do
      brave = Brave.create! valid_attributes
      delete :destroy, :id => brave.id.to_s
      response.should redirect_to(braves_url)
    end
  end

end
