require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HuntersController do

  # This should return the minimal set of attributes required to create a valid
  # Hunter. As you add validations to Hunter, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all hunters as @hunters" do
      hunter = Hunter.create! valid_attributes
      get :index
      assigns(:hunters).should eq([hunter])
    end
  end

  describe "GET show" do
    it "assigns the requested hunter as @hunter" do
      hunter = Hunter.create! valid_attributes
      get :show, :id => hunter.id.to_s
      assigns(:hunter).should eq(hunter)
    end
  end

  describe "GET new" do
    it "assigns a new hunter as @hunter" do
      get :new
      assigns(:hunter).should be_a_new(Hunter)
    end
  end

  describe "GET edit" do
    it "assigns the requested hunter as @hunter" do
      hunter = Hunter.create! valid_attributes
      get :edit, :id => hunter.id.to_s
      assigns(:hunter).should eq(hunter)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Hunter" do
        expect {
          post :create, :hunter => valid_attributes
        }.to change(Hunter, :count).by(1)
      end

      it "assigns a newly created hunter as @hunter" do
        post :create, :hunter => valid_attributes
        assigns(:hunter).should be_a(Hunter)
        assigns(:hunter).should be_persisted
      end

      it "redirects to the created hunter" do
        post :create, :hunter => valid_attributes
        response.should redirect_to(Hunter.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved hunter as @hunter" do
        # Trigger the behavior that occurs when invalid params are submitted
        Hunter.any_instance.stub(:save).and_return(false)
        post :create, :hunter => {}
        assigns(:hunter).should be_a_new(Hunter)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Hunter.any_instance.stub(:save).and_return(false)
        post :create, :hunter => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested hunter" do
        hunter = Hunter.create! valid_attributes
        # Assuming there are no other hunters in the database, this
        # specifies that the Hunter created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Hunter.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => hunter.id, :hunter => {'these' => 'params'}
      end

      it "assigns the requested hunter as @hunter" do
        hunter = Hunter.create! valid_attributes
        put :update, :id => hunter.id, :hunter => valid_attributes
        assigns(:hunter).should eq(hunter)
      end

      it "redirects to the hunter" do
        hunter = Hunter.create! valid_attributes
        put :update, :id => hunter.id, :hunter => valid_attributes
        response.should redirect_to(hunter)
      end
    end

    describe "with invalid params" do
      it "assigns the hunter as @hunter" do
        hunter = Hunter.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Hunter.any_instance.stub(:save).and_return(false)
        put :update, :id => hunter.id.to_s, :hunter => {}
        assigns(:hunter).should eq(hunter)
      end

      it "re-renders the 'edit' template" do
        hunter = Hunter.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Hunter.any_instance.stub(:save).and_return(false)
        put :update, :id => hunter.id.to_s, :hunter => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested hunter" do
      hunter = Hunter.create! valid_attributes
      expect {
        delete :destroy, :id => hunter.id.to_s
      }.to change(Hunter, :count).by(-1)
    end

    it "redirects to the hunters list" do
      hunter = Hunter.create! valid_attributes
      delete :destroy, :id => hunter.id.to_s
      response.should redirect_to(hunters_url)
    end
  end

end
