require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LinesController do

  # This should return the minimal set of attributes required to create a valid
  # Line. As you add validations to Line, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all lines as @lines" do
      line = Line.create! valid_attributes
      get :index
      assigns(:lines).should eq([line])
    end
  end

  describe "GET show" do
    it "assigns the requested line as @line" do
      line = Line.create! valid_attributes
      get :show, :id => line.id.to_s
      assigns(:line).should eq(line)
    end
  end

  describe "GET new" do
    it "assigns a new line as @line" do
      get :new
      assigns(:line).should be_a_new(Line)
    end
  end

  describe "GET edit" do
    it "assigns the requested line as @line" do
      line = Line.create! valid_attributes
      get :edit, :id => line.id.to_s
      assigns(:line).should eq(line)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Line" do
        expect {
          post :create, :line => valid_attributes
        }.to change(Line, :count).by(1)
      end

      it "assigns a newly created line as @line" do
        post :create, :line => valid_attributes
        assigns(:line).should be_a(Line)
        assigns(:line).should be_persisted
      end

      it "redirects to the created line" do
        post :create, :line => valid_attributes
        response.should redirect_to(Line.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved line as @line" do
        # Trigger the behavior that occurs when invalid params are submitted
        Line.any_instance.stub(:save).and_return(false)
        post :create, :line => {}
        assigns(:line).should be_a_new(Line)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Line.any_instance.stub(:save).and_return(false)
        post :create, :line => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested line" do
        line = Line.create! valid_attributes
        # Assuming there are no other lines in the database, this
        # specifies that the Line created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Line.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => line.id, :line => {'these' => 'params'}
      end

      it "assigns the requested line as @line" do
        line = Line.create! valid_attributes
        put :update, :id => line.id, :line => valid_attributes
        assigns(:line).should eq(line)
      end

      it "redirects to the line" do
        line = Line.create! valid_attributes
        put :update, :id => line.id, :line => valid_attributes
        response.should redirect_to(line)
      end
    end

    describe "with invalid params" do
      it "assigns the line as @line" do
        line = Line.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Line.any_instance.stub(:save).and_return(false)
        put :update, :id => line.id.to_s, :line => {}
        assigns(:line).should eq(line)
      end

      it "re-renders the 'edit' template" do
        line = Line.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Line.any_instance.stub(:save).and_return(false)
        put :update, :id => line.id.to_s, :line => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested line" do
      line = Line.create! valid_attributes
      expect {
        delete :destroy, :id => line.id.to_s
      }.to change(Line, :count).by(-1)
    end

    it "redirects to the lines list" do
      line = Line.create! valid_attributes
      delete :destroy, :id => line.id.to_s
      response.should redirect_to(lines_url)
    end
  end

end
