require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SmartsController do

  # This should return the minimal set of attributes required to create a valid
  # Smart. As you add validations to Smart, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all smarts as @smarts" do
      smart = Smart.create! valid_attributes
      get :index
      assigns(:smarts).should eq([smart])
    end
  end

  describe "GET show" do
    it "assigns the requested smart as @smart" do
      smart = Smart.create! valid_attributes
      get :show, :id => smart.id.to_s
      assigns(:smart).should eq(smart)
    end
  end

  describe "GET new" do
    it "assigns a new smart as @smart" do
      get :new
      assigns(:smart).should be_a_new(Smart)
    end
  end

  describe "GET edit" do
    it "assigns the requested smart as @smart" do
      smart = Smart.create! valid_attributes
      get :edit, :id => smart.id.to_s
      assigns(:smart).should eq(smart)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Smart" do
        expect {
          post :create, :smart => valid_attributes
        }.to change(Smart, :count).by(1)
      end

      it "assigns a newly created smart as @smart" do
        post :create, :smart => valid_attributes
        assigns(:smart).should be_a(Smart)
        assigns(:smart).should be_persisted
      end

      it "redirects to the created smart" do
        post :create, :smart => valid_attributes
        response.should redirect_to(Smart.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved smart as @smart" do
        # Trigger the behavior that occurs when invalid params are submitted
        Smart.any_instance.stub(:save).and_return(false)
        post :create, :smart => {}
        assigns(:smart).should be_a_new(Smart)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Smart.any_instance.stub(:save).and_return(false)
        post :create, :smart => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested smart" do
        smart = Smart.create! valid_attributes
        # Assuming there are no other smarts in the database, this
        # specifies that the Smart created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Smart.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => smart.id, :smart => {'these' => 'params'}
      end

      it "assigns the requested smart as @smart" do
        smart = Smart.create! valid_attributes
        put :update, :id => smart.id, :smart => valid_attributes
        assigns(:smart).should eq(smart)
      end

      it "redirects to the smart" do
        smart = Smart.create! valid_attributes
        put :update, :id => smart.id, :smart => valid_attributes
        response.should redirect_to(smart)
      end
    end

    describe "with invalid params" do
      it "assigns the smart as @smart" do
        smart = Smart.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Smart.any_instance.stub(:save).and_return(false)
        put :update, :id => smart.id.to_s, :smart => {}
        assigns(:smart).should eq(smart)
      end

      it "re-renders the 'edit' template" do
        smart = Smart.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Smart.any_instance.stub(:save).and_return(false)
        put :update, :id => smart.id.to_s, :smart => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested smart" do
      smart = Smart.create! valid_attributes
      expect {
        delete :destroy, :id => smart.id.to_s
      }.to change(Smart, :count).by(-1)
    end

    it "redirects to the smarts list" do
      smart = Smart.create! valid_attributes
      delete :destroy, :id => smart.id.to_s
      response.should redirect_to(smarts_url)
    end
  end

end
